---
common:
  environment: dev
  ingress:
    host: skalazhato.nemes.local
    paths:
      recipeService: /recipe
      mealplanService: /planner

  database:
    postgres:
      username: postgres
      password: Asdasd11
      database: mealplanner
      host: postgresql.postgresql.svc.cluster.local
      port: 5432

recipeService:
  replicaCount: 1

  image:
    repository: recipe
    tag: ""

  service:
    enabled: true
    type: ClusterIP
    port: 80

  podAnnotations: {}
  podLabels: {}

  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

  horizontalScaler:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    isDemo: true
    resources:
      cpu: 50
      memory: 50

  env:
    # Options: 'critical', 'error', 'warning', 'info', 'debug', 'trace'. Default: 'info'.
    logLevel: debug

mealplanService:
  replicaCount: 1

  image:
    repository: mealplan
    tag: ""

  service:
    enabled: true
    type: ClusterIP
    port: 80

  podAnnotations: {}
  podLabels: {}

  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

  horizontalScaler:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    isDemo: true
    resources:
      cpu: 50
      memory: 50

  env:
    # Options: 'critical', 'error', 'warning', 'info', 'debug', 'trace'. Default: 'info'.
    logLevel: debug

backuper:
  image:
    repository: postgres
    tag: 18
  pvc:
    enabled: true
    hostPath: /mnt/backups
    size: 5Gi
