apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-postgres-credentials
  namespace: {{ .Release.Namespace }}
  type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.common.database.postgres.username }}
  password: {{ .Values.common.database.postgres.password }}
