{{- if .Values.mealplanService.horizontalScaler.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-mealplan-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}-{{ .Release.Name }}-mealplan-service
  minReplicas: {{ .Values.mealplanService.horizontalScaler.minReplicas }}
  maxReplicas: {{ .Values.mealplanService.horizontalScaler.maxReplicas }}
  metrics:
    {{- range $resource, $threshold := .Values.mealplanService.horizontalScaler.resources }}
    - type: Resource
      resource:
        name: {{ $resource }}
        target:
          type: Utilization
          averageUtilization: {{ $threshold }}
    {{- end }}
  {{- if .Values.mealplanService.horizontalScaler.isDemo }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
        - type: Percent
          value: 50
          periodSeconds: 5
  {{- end }}
{{- end }}
