apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-mealplan-service
  namespace: {{ .Release.Namespace }}
data:
  logLevel: {{ .Values.mealplanService.env.logLevel | quote }}
  rootPath: {{ .Values.common.ingress.paths.mealplanService }}
