apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-mealplan-service
  namespace: {{ .Release.Namespace }}
data:
  logLevel: {{ .Values.mealplanService.env.logLevel | quote }}
  rootPath: {{ .Values.common.ingress.paths.mealplanService }}
  redisHost: {{ .Values.common.database.redis.host }}
  redisPort: {{ .Values.common.database.redis.port | quote }}
  recipeServiceHost: {{ .Chart.Name }}-{{ .Release.Name }}-recipe-service
  recipeServiceNamespace: {{ .Release.Namespace }}
