apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-backuper
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.backuper.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgresql-backuper
            image: "{{ .Values.backuper.image.repository }}:{{ .Values.backuper.image.tag }}"
            command: ["/bin/bash", "/scripts/backup.sh"]
            env:
              - name: POSTGRES_HOST
                value: {{ .Values.common.database.postgres.host }}
              - name: POSTGRES_DATABASE
                value: {{ .Values.common.database.postgres.database }}
              - name: POSTGRES_PORT
                value: {{ .Values.common.database.postgres.port | quote}}
              - name: POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: {{ .Chart.Name }}-{{ .Release.Name }}-postgres-credentials
                    key: username
              - name: POSTGRES_PASS
                valueFrom:
                  secretKeyRef:
                    name: {{ .Chart.Name }}-{{ .Release.Name }}-postgres-credentials
                    key: password
            volumeMounts:
              - name: backup-script
                mountPath: /scripts
                readOnly: true
              - name: backup-storage
                mountPath: /backups
          restartPolicy: OnFailure
          volumes:
            - name: backup-script
              configMap:
                name: {{ .Chart.Name }}-{{ .Release.Name }}-backuper-script
                defaultMode: 0755
            {{- if .Values.backuper.pvc.enabled }}
            - name: backup-storage
              persistentVolumeClaim:
                claimName: {{ .Chart.Name }}-{{ .Release.Name }}-backup-pvc
            {{- else }}
            - name: backup-storage
              emptyDir: {}
            {{- end }}
