apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-service
spec:
  replicas: {{ .Values.recipeService.replicaCount }}
  selector:
    matchLabels:
      app: recipe-service
  template:
    metadata:
      labels:
        app: recipe-service
        {{- with .Values.recipeService.podLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: recipe-service
        image: "{{ .Values.recipeService.image.repository }}:{{ .Values.recipeService.image.tag }}"
        ports:
        - containerPort: 80
