apiVersion: v1
kind: Service
metadata:
  name: recipe-service
spec:
  selector:
    app: recipe-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.recipeService.service.port }}
